### PR TITLE
Give an option to choose a file name of your own

### PR DESCRIPTION
**Pull request by s7dhansh**
options.file_name feature. If you like and approve the feature, I will edit the readme.

### CODE REVIEW

**Comment by s7dhansh** [comment]
I think a better option would be to have another field in the file object itself, eg. file.upload_name. It will ensure that ops.file/ops.files, both work consistently without any changes to the core structure of the file. What say @Lepozepo ?

I faced the requirement of such a feature because of Dropzone.js. The file is used in so many events that changing its inherent name does not make sense, and using a pre generated unique name helps me in my app. I would like to use the same name at S3.

**Comment by Lepozepo** [comment]
Hey @s7dhansh! Sorry for the late reply. If you could edit the README before I merge that would be great. I think something like an upload_name should work as a function so that inside of a loop you can change the file name dynamically

**Comment by s7dhansh** [comment]
@Lepozepo Kindly review

**Comment by Lepozepo** [comment]
Sweet! Thanks @s7dhansh

**Pull request merged**
