### PR TITLE
server side encryption

### PR DESCRIPTION
**Pull request by tscizzle**

### CODE REVIEW

**Comment by Lepozepo** [comment]
@tscizzle this looks awesome! Have you tested it?

**Comment by tscizzle** [comment]
Is there an automated test suite? I did not run anything automated or rigorous.

I basically made some changes locally in my app, and successfully uploaded to S3 (encrypted, and not encrypted), and then copied those changes into this fork for the pull request.

**Comment by Lepozepo** [comment]
Good enough for me :D thanks for the PR, will merge tomorrow at some point and bump versions.

**Comment by tscizzle** [comment]
Bumping, so this doesn't fall through the cracks.

Also, do you publish to atmosphere right after merging and bumping version?

**Comment by Lepozepo** [comment]
@tscizzle yep!

**Comment by Lepozepo** [comment]
All set @tscizzle, thank you for the support!

**Pull request merged**
