### PR TITLE
used npm package base64 string to s3 to make uploads work with mdg:camera

### PR DESCRIPTION
**Pull request by kevohagan**
Needs proper docs + testing + error handling etc

but its a first working copy ;)

### CODE REVIEW

**Comment by geritol** [comment]
any update on this integration? @Lepozepo

**Comment by Lepozepo** [comment]
Hey guys, sorry I haven't had a chance to work on this. Just finished a big project, hope to update the package soon.

**Comment by geritol** [comment]
hi! any news on this?

**Comment by nathanwaters** [comment]
+1 looking for this functionality

**Comment by geritol** [comment]
hi! any news?

**Comment by Lepozepo** [comment]
Hey @geritol, I just updated the package uploader to a client-side only uploader so that the server doesn't spend any resources. I think the uploader is already compatible with base64 but I have not tested it yet. Let me check if amazon has any requirements on headers for base64.

**Comment by Lepozepo** [comment]
Ok, just had a look. My package needs an option that will turn the base64 into a blob. The solution would be something similar to [this](http://blog.danguer.com/2011/10/25/upload-s3-files-directly-with-ajax/). I'll see if I get a chance to address it this coming weekend.

**Pull request closed without merging**
